// <auto-generated />
using System;
using DomainLayer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DomainLayer.Migrations
{
    [DbContext(typeof(AHUBContext))]
    [Migration("20230914125649_PasswordChangeTimeAdded")]
    partial class PasswordChangeTimeAdded
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DomainLayer.Models.PasswordChanges", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("changePasswordBefore")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("dateTimeAdded")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("keyValidBefore")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("passwordChangeTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("recoveryKey")
                        .HasColumnType("integer");

                    b.Property<Guid>("userId")
                        .HasColumnType("uuid");

                    b.HasKey("id");

                    b.HasIndex("userId");

                    b.ToTable("PasswordChanges", (string)null);
                });

            modelBuilder.Entity("DomainLayer.Models.User", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("birthday")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("dateTimeAdded")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("educationInfo")
                        .HasColumnType("text");

                    b.Property<string>("firstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<short?>("gender")
                        .HasColumnType("smallint");

                    b.Property<string>("hashedPassword")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("homeTown")
                        .HasColumnType("text");

                    b.Property<string>("jobInfo")
                        .HasColumnType("text");

                    b.Property<string>("lastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("salt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("userName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("id");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("DomainLayer.Models.PasswordChanges", b =>
                {
                    b.HasOne("DomainLayer.Models.User", "user")
                        .WithMany("PasswordChanges")
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("user");
                });

            modelBuilder.Entity("DomainLayer.Models.User", b =>
                {
                    b.Navigation("PasswordChanges");
                });
#pragma warning restore 612, 618
        }
    }
}
